%% Replacement for the two plotting sections in Knee_Extensor_20mm.m
% Uses your existing T, T_ICR_t1, T_Pam, phi, pos, p1, pEnd, Location,
% CrossPoint, positions and vastii objects. Does not rebuild any transforms.

%% Static muscle/bone plot at exactly zero knee angle
bonePlotArgs = {T,T_ICR_t1,phi,pos,p1,pEnd, ...
    {Vas_Int,Vas_Lat,Vas_Med}, ...
    'DisplayRotation',eye(3), ...
    'DisplayAxisMap',eye(3), ...
    'Location',Location,'CrossPoint',CrossPoint,'T_Pam',T_Pam, ...
    'HumanLabels',{'Vastus Intermedius','Vastus Lateralis','Vastus Medialis'}, ...
    'CameraOrbitDeg',90, ...
    'XLim',[],'YLim',[],'ZLim',[]};

run('MuscleBonePlotting.m')

%% Moving muscle/bone plot: zero -> full flexion -> full extension -> zero
frames = [pos:-1:1, 2:positions, positions-1:-1:pos];

AnimateKneeBoneMuscle(bonePlotArgs{:}, ...
    'FullSkeleton',true, ... % true = full skeleton; false = femur/tibia only
    'FrameIndices',frames,'PauseTime',0.02,'Loop',false, ...
    'ExportGif',true, ...
    'GifFile','Knee_Extensor_20mm.gif', ...
    'FrameRate',20);

clear bonePlotArgs
