"""Build Ben's AnimatLab Walker_2_Layer_CPG_BilateralRG architecture in
sns-toolbox (the "W2L" contact-driven two-layer CPG).

WIRING SOURCE OF TRUTH (this module designs NO topology - it transcribes):
  spinal/connectome_templates.json, key "bilateralrg"
  (105 nodes / 226 edges, each edge carries sign + gain + tag). That template
  was generated by spinal/make_editor_templates.py > build_bilateralrg() as the
  W2L base (mined from Walker_2_Layer_CPG.aproj) plus the DOCUMENTED build chain
  of Neuromechanical_Models/Walker_2_Layer_CPG_BilateralRG/tools/
  SESSION_NOTES_20260916.md:
      build_rg.pl          R half-center ipsilateral to R PF, the 4 crossed
                           L-RG->R-PF connexions removed, Stimulus_2 kickoff
      build_comm.pl +      Shinohara c1 / V3 commissurals (SynAmp 2.749 inh /
      patch_comm_types.pl  0.1 weak exc; RG-Excite at 2.749 LATCHES both RGs)
      build_aff.pl         flexor Ia and extensor Ib excite their HCs (0.01)
      build_contact.pl     heel/toe contact -> ipsilateral extensor layers (C=20)
Every synapse added here keeps the template tag, so any edge can be traced
straight back to the template / SESSION_NOTES step.

NODE MAPPING (template type -> sns-toolbox 1.5.2):
  HC-RG-E / HC-RG-F   NonSpikingNeuronWithPersistentSodiumChannel with the
                      SAME parameter set as the proven spinal RG
                      (spinal/params.py NAP; spinal/build_network.py:370),
                      stepped by SNS_NumpyFixedTau (imported read-only from
                      spinal/build_network.py) because the STOCK
                      voltage-dependent tau_h(V) quenches these half-centers
                      (measured 2026-09-16, AGENTS.md correction; AnimatLab
                      treats tau_h.max as a FIXED constant - same semantics).
  every other neuron  NonSpikingNeuron (graded RC neuron, 0..5 mV scale).
  MUSCLE              network OUTPUT port of its MN (add_output). The
                      template's mn_to_muscle edge (exc, 1.0) is an implied
                      pass-through, not a synapse.
  PORT-load           current INPUT port on that node's single edge target.
                      (AnimatLab TonicCurrent stimuli = current sources. The
                      .aproj waveform, read from
                      Walker_2_Layer_CPG_BilateralRG.aproj: BOTH Stimulus_1
                      (into L RG ext) and Stimulus_2 (into R RG flx) are
                      10 nA, active t in [0, 0.01 s] - the antiphase kickoff
                      pair. The waveform lives in the caller (smoke_w2l.py),
                      exactly where a MuJoCo runner would drive the ports.)
  SN-heel / SN-toe    graded contact-encoder NEURONS with an input port
                      (deviation: AnimatLab's are SPIKING contact cells; the
                      graded port matches the existing stack's HEEL_c/TOE_c
                      ports, spinal/build_network.py:436-447, and keeps this
                      package numpy-backend-only. The 20-edge contact wiring
                      out of these neurons is transcribed verbatim.)

CONDUCTANCE MAPPING (AnimatLab SynAmp -> toolbox max_conductance): the
SESSION_NOTES mechanics section proved the per-connexion <G> is IGNORED by
AnimatSimulator - the EFFECTIVE strength is the synapse TYPE's SynAmp, which
the template carries in its tags. AnimatLab runs Equil -50..-70 mV neurons;
this package runs the repo's 0..5 mV scale, so the SynAmps are re-expressed
per pathway with the closest PROVEN value from the existing spinal stack
(each entry cites its source). Relative magnitudes are preserved:
c1 strong, V3 weak, afferent-HC-excite very weak, generic connexions uniform.

USAGE
    net = build()                      # loads ../connectome_templates.json
    u = net.make_inputs()              # zeros, ordered like net.inputs
    u[net.input_index("Stimulus_1")] = 10.0   # nA
    V = net.step(u)                    # one dt; V indexed by net.idx
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

from sns_toolbox.connections import NonSpikingSynapse
from sns_toolbox.neurons import (NonSpikingNeuron,
                                 NonSpikingNeuronWithPersistentSodiumChannel)
from sns_toolbox.networks import Network

# The fixed-tau_h backend patch is shared with the main spinal stack (one
# place to re-diff against sns_toolbox upgrades). Read-only import: nothing
# in this package writes to spinal/.
HERE = Path(__file__).parent
SPINAL = HERE.parent
if str(SPINAL) not in __import__("sys").path:
    __import__("sys").path.insert(0, str(SPINAL))
from build_network import SNS_NumpyFixedTau  # noqa: E402

# --------------------------------------------------------------- scale / units
# Identical conventions to spinal/build_network.py:151-154 and params.py:26-27.
E_HI = 5.0            # mV, presynaptic saturation point (= "full activation")
DT = 0.002            # s, repo stepping convention (params.DT)
SYN_E_LO, SYN_E_HI = 0.0, E_HI
E_REV_EXC = 8.0       # mV, excitatory reversal (build_network.py:153)
E_REV_INH = -E_HI     # mV, inhibitory reversal (build_network.py:154)

# --------------------------------------------------------------- time constants
# Copied from spinal/params.py TAU (values cited there); W2L deviations marked.
TAU = dict(
    mn=0.03,          # MN pool (params.TAU["mn"])
    afferent=0.02,    # SN-Ia / SN-Ib encoders + IaIN (params.TAU["afferent"])
    rg=0.05,          # RG-layer membrane: half-centers, InE/InF, c1/V3
    rg_nap_h=0.25,    # W2L VALUE. The FIXED h-gate tau = the PERIOD knob
                      # (measured ~3.3-4.3x linear scaling, spinal/
                      # _nap_fixed_test.py 2026-09-16): 0.35 s -> ~1.2 s cycle
                      # (the stack's walking value); 0.25 s -> ~1.0 s so the
                      # intrinsic period matches the smoke's ~1 Hz contact
                      # cadence and the 0.5 s L/R bang offset is true
                      # antiphase (at 0.30 the period ran 1.3 s and the same
                      # 0.5 s offset only reached r ~ -0.45). Tune here.
    pf=0.08,          # PF half-centers + PF cross-INs (params.TAU["pf"])
    rc=0.03,          # Renshaw cells (mn tau, as in the stack)
    contact=0.04,     # heel/toe encoder neurons (params.TAU["preset"] legacy)
)

# Persistent-Na half-center parameters - VERBATIM spinal/params.py NAP except
# tau_max_h (see TAU above). Measured regime: plateau ~2 mV threshold, burst
# termination by the fixed-tau h-gate.
NAP = dict(
    g_ion=12.0,
    e_ion=8.0,
    k_m=1.0, slope_m=0.8, e_m=2.0,
    k_h=1.0, slope_h=-2.0, e_h=3.5,
    tau_max_h=TAU["rg_nap_h"],
)

# --------------------------------------------------------------- gain mapping
# tag (template) -> toolbox max_conductance. Keys "exc"/"inh" where the two
# directions of a tag differ. Every entry cites its source; 'template' values
# are the AnimatLab SynAmp magnitudes the entry re-expresses.
W2L_GAINS = dict(
    # RG laminated inhibition E->InE, InE->F, F->InF, InF->E: the stack's
    # proven rg_mutual_inh (params.G, used on the identical NaP half-center
    # architecture, build_network.py:392-395). Template SynAmp 0.5.
    rg_laminate=4.0,
    # DIRECT RG-E<->RG-F excitation (template tag rg_laminate, exc, HC->HC
    # only): the W2L escape-mode assist. Kept WEAK at the template's raw 0.5 -
    # strong mutual excitation on this architecture latches both HCs
    # (measured 2026-09-16, params.G["rg_weak_exc"] note / Deng 2022 G_W).
    rg_direct_exc=0.5,
    # RG -> its PF half-centers: stack rg_to_pf (params.G). Template 0.5.
    pf_drive=2.4,
    # PF cross-inhibition PF->PF-IN->antagonist: stack pf_recip_inh. Template 0.5.
    pf_cross=4.0,
    # PF -> MN: stack pf_to_mn. Template 0.5.
    pf_to_mn=2.0,
    # Renshaw: MN->RC exc 1.0 and RC->MN inh 0.5, RC<->RC inh 0.5 - the stack's
    # Deng-A6 values (build_network.py:746-747,755; params.G["renshaw"] 0.5 ran
    # 2026-09-14). Template SynAmp 0.5.
    rc_own_exc=1.0,
    rc_inh=0.5,
    # Ia sensory -> IaIN exc = stack ia_to_mn; IaIN -> antagonist MN inh =
    # stack ia_to_antagonist (params.G). Template 0.5.
    ia_sn_exc=0.6,
    ia_inh=0.4,
    # IaIN <-> antagonist IaIN mutual inhibition: Deng A6 0.5
    # (build_network.py:798). Template 0.5.
    ia_mutual=0.5,
    # Ib autogenic EXCITATION of the homonymous MN (stance reflex reversal as
    # wired in the template; the template's aff build also drives extensor
    # HCs, same family as stack ib_group_exc 0.5, params.G). Template 0.5.
    ib_auto=0.5,
    # PF -> IaIN phase gate and RC -> IaIN disinhibition ('other' tag): the
    # stack uses exactly 0.5 for both (build_network.py:776, 779). Template 0.5.
    other=0.5,
    # Afferent -> HC excitation ("Afferent HC Excite" SynAmp 0.01 vs generic
    # 0.5 = 2%): kept proportionally tiny vs the 4.0 RG family.
    aff_HC_excite=0.08,
    # Shinohara commissurals. AnimatLab: RG_F->c1 1.0, c1->contra RG_F 2.749
    # (inh); V3 legs 1.0 / 0.1 / 0.1 (weak - the 09-16 anti-latch fix,
    # SESSION_NOTES step 3). c1_inh 3.0 locks the two sides' periods
    # (measured 2026-09-24: at 2.0 the sides ran 1.05 vs 1.10 s free-running
    # and the phase drifted; at 3.0/4.0 the periods lock identical). The
    # earlier follower-suppression at strong c1 was the MISSING R-side
    # direct-excitation mirror (see MIRROR FIX), not the c1 strength.
    # v3_weak 0.08 keeps the template's ~4% c1:V3 ratio; full-strength V3
    # E-latches both sides (params.G note).
    comm_c1=1.0,
    c1_inh=3.0,
    comm_v3=1.0,
    v3_weak=0.08,
    # Contact-neuron OUTPUT synapses (24 edges). The template's gain 20 is the
    # ANIMATLAB ADAPTER current gain (nA per contact into the contact neuron),
    # NOT a synapse strength - the adapter value is applied smoke-side
    # (CONTACT_CURRENT_NA = 20) and these synapses carry a generic excitatory
    # strength (strong: contact must flip the extensor layers, but below the
    # 4.0 that latches; SESSION_NOTES: contact C=20 is a tuning knob).
    contact=1.0,
)

# template node type -> membrane tau key
_TYPE_TAU = {
    "HC-RG-E": "rg", "HC-RG-F": "rg",
    "IN-InE": "rg", "IN-InF": "rg",
    "IN-C": "rg", "IN-V3": "rg",
    "HC-PF-E": "pf", "HC-PF-F": "pf", "IN-PF": "pf",
    "IN-IaIN": "afferent", "SN-Ia": "afferent", "SN-Ib": "afferent",
    "MN": "mn", "RC": "rc", "SN-heel": "contact", "SN-toe": "contact",
}


def _neu(tau: float) -> NonSpikingNeuron:
    return NonSpikingNeuron(membrane_capacitance=float(tau),
                            membrane_conductance=1.0,
                            resting_potential=0.0, bias=0.0)


def _syn(g: float, exc: bool) -> NonSpikingSynapse:
    return NonSpikingSynapse(max_conductance=float(g),
                             reversal_potential=E_REV_EXC if exc else E_REV_INH,
                             e_lo=SYN_E_LO, e_hi=SYN_E_HI)


@dataclass
class W2LNet:
    """Compiled wrapper over the transcribed W2L network (same interface as
    the stack's SpinalNetwork: idx / inputs / make_inputs / step)."""
    template: dict
    gains: dict = field(default_factory=dict)   # merged over W2L_GAINS
    net: Network = field(init=False)
    compiled: object = field(init=False, default=None)
    idx: dict = field(default_factory=dict)
    inputs: list = field(default_factory=list)   # ordered input-port names
    port_targets: dict = field(default_factory=dict)  # port name -> neuron
    muscle_outputs: dict = field(default_factory=dict)  # muscle label -> MN
    synapse_counts: dict = field(default_factory=dict)  # tag -> n synapses
    n_synapses: int = field(init=False, default=0)

    # ------------------------------------------------------------------ build
    def __post_init__(self):
        self.G = dict(W2L_GAINS)
        self.G.update(self.gains or {})
        tpl = self.template
        nodes = {n["label"]: n for n in tpl["nodes"]}
        edges = tpl["edges"]
        self.net = Network(name="W2L bilateral contact-driven CPG")

        # sanity: template edges must all resolve to known nodes
        for e in edges:
            for k in ("from", "to"):
                if e[k] not in nodes:
                    raise ValueError(f"template edge endpoint unknown: {e}")

        # ---- neurons: every non-MUSCLE, non-PORT-load node, template order
        for nd in tpl["nodes"]:
            lab, typ = nd["label"], nd["type"]
            if typ in ("MUSCLE", "PORT-load"):
                continue
            tau_key = _TYPE_TAU[typ]
            if typ in ("HC-RG-E", "HC-RG-F"):
                nap = NonSpikingNeuronWithPersistentSodiumChannel(
                    membrane_capacitance=TAU["rg"], membrane_conductance=1.0,
                    resting_potential=0.0, bias=0.0,
                    g_ion=np.array([NAP["g_ion"]]),
                    e_ion=np.array([NAP["e_ion"]]),
                    k_m=np.array([NAP["k_m"]]),
                    slope_m=np.array([NAP["slope_m"]]),
                    e_m=np.array([NAP["e_m"]]),
                    k_h=np.array([NAP["k_h"]]),
                    slope_h=np.array([NAP["slope_h"]]),
                    e_h=np.array([NAP["e_h"]]),
                    tau_max_h=np.array([NAP["tau_max_h"]]))
                self.net.add_neuron(nap, name=lab)
            else:
                self.net.add_neuron(_neu(TAU[tau_key]), name=lab)
            self.idx[lab] = len(self.idx)

        # ---- input ports: SN-heel/toe (contact neurons) and PORT-load
        # (AnimatLab TonicCurrent stimuli -> current port on the edge target).
        outgoing = {}
        for e in edges:
            outgoing.setdefault(e["from"], []).append(e)
        for nd in tpl["nodes"]:
            lab, typ = nd["label"], nd["type"]
            if typ in ("SN-heel", "SN-toe"):
                self.net.add_input(lab)
                self.inputs.append(lab)
                self.port_targets[lab] = lab
            elif typ == "PORT-load":
                outs = outgoing.get(lab, [])
                if len(outs) != 1:
                    raise ValueError(f"{lab}: expected 1 outgoing edge, "
                                     f"got {len(outs)}")
                tgt = outs[0]["to"]
                self.net.add_input(tgt)
                self.inputs.append(lab)      # port keeps the stimulus name
                self.port_targets[lab] = tgt

        # ---- TONIC drive ports on the four RG half-centers (NOT in the
        # AnimatLab template - the template is purely contact-driven). The
        # smoke's "constant mild drive" and, later, a MuJoCo runner's DRIVE
        # land here, following the stack's DRIVE convention where BOTH
        # half-centers of a side carry tonic drive (params.G descend_to_rg_e
        # 1.7 / descend_to_rg_f 1.4): without F-side drive the F half-center
        # can never take over from an E plateau and the RG latches in
        # extension (measured in the first smoke run, 2026-09-24). Current
        # ports add no synapses - zero current leaves the graph unchanged.
        for lab in ("L RG ext", "L RG flx", "R RG ext", "R RG flx"):
            port = "TONIC " + lab
            self.net.add_input(lab)
            self.inputs.append(port)
            self.port_targets[port] = lab

        # ---- muscles: output ports of their MN (the mn_to_muscle edge is an
        # implied pass-through, g=1.0, no synapse)
        for e in edges:
            if e["tag"] == "mn_to_muscle":
                self.net.add_output(e["from"], name=e["to"])
                self.muscle_outputs[e["to"]] = e["from"]

        # ---- synapses: every remaining edge, per-tag conductance
        n_types = {lab: nd["type"] for lab, nd in nodes.items()}
        for e in edges:
            tag, sign = e["tag"], e["sign"]
            if tag == "mn_to_muscle":
                continue
            if n_types[e["from"]] == "PORT-load":
                continue                     # stimulus edges -> ports, above
            g = self._gain(tag, sign, e, n_types)
            self.net.add_connection(_syn(g, exc=(sign == "exc")),
                                    e["from"], e["to"])
            self.synapse_counts[tag] = self.synapse_counts.get(tag, 0) + 1
            self.n_synapses += 1

        # ---- MIRROR FIX (documented deviation, 2 edges): the template's
        # rg_laminate group carries the L-side direct half-center excitation
        # (L RG ext->L RG flx, L RG flx->L RG ext, g 0.5) but NOT the R-side
        # mirrors - make_editor_templates.py>build_bilateralrg step 1 adds
        # only the 4 laminated edges for the R block. SESSION_NOTES line 85:
        # "R RG half-center mirrors the L RG block exactly". Without them the
        # R pair has no escape assist and CANNOT oscillate while L does
        # (measured 2026-09-24: every bilateral smoke run pinned R in
        # extension). Added here with the L side's own gain (rg_direct_exc).
        for src, dst in (("R RG ext", "R RG flx"), ("R RG flx", "R RG ext")):
            self.net.add_connection(_syn(self.G["rg_direct_exc"], exc=True),
                                    src, dst)
            self.synapse_counts["rg_laminate_mirror"] = \
                self.synapse_counts.get("rg_laminate_mirror", 0) + 1
            self.n_synapses += 1

        self._assert_complete(edges, n_types)

    # ------------------------------------------------------------------ parts
    def _gain(self, tag: str, sign: str, e: dict, n_types: dict) -> float:
        """Template (tag, sign) -> toolbox conductance (see W2L_GAINS)."""
        G = self.G
        if tag == "rg_laminate":
            if n_types[e["from"]] in ("HC-RG-E", "HC-RG-F") and \
                    n_types[e["to"]] in ("HC-RG-E", "HC-RG-F"):
                return G["rg_direct_exc"]    # direct HC<->HC escape excitation
            return G["rg_laminate"]
        if tag == "pf_drive":
            return G["pf_drive"]
        if tag == "pf_cross":
            return G["pf_cross"]
        if tag == "pf_to_mn":
            return G["pf_to_mn"]
        if tag == "rc_own":
            return G["rc_own_exc"] if sign == "exc" else G["rc_inh"]
        if tag == "rc_mutual":
            return G["rc_inh"]
        if tag == "ia_recip":
            return G["ia_sn_exc"] if sign == "exc" else G["ia_inh"]
        if tag == "ia_mutual":
            return G["ia_mutual"]
        if tag == "ib_auto":
            return G["ib_auto"]
        if tag == "other":
            return G["other"]
        if tag == "aff_HC_excite":
            return G["aff_HC_excite"]
        if tag == "comm_c1":
            return G["comm_c1"]
        if tag == "c1_SynAmp2.749":
            return G["c1_inh"]
        if tag == "comm_v3":
            return G["comm_v3"]
        if tag in ("v3_SynAmp0.1_weak", "v3_to_contra_InE"):
            return G["v3_weak"]
        if tag == "contact_C20":
            return G["contact"]
        if tag == "kickoff_antiphase":
            raise ValueError("kickoff edge should have become a port")
        raise ValueError(f"unknown template tag: {tag}")

    def _assert_complete(self, edges, n_types):
        expected = {}
        for e in edges:
            if e["tag"] == "mn_to_muscle":
                continue
            if n_types[e["from"]] == "PORT-load":
                continue
            expected[e["tag"]] = expected.get(e["tag"], 0) + 1
        assert self.n_synapses == sum(expected.values()) + 2 == 214, \
            f"synapse transcription mismatch: {self.n_synapses} vs 214 " \
            f"(212 template + 2 mirror-fix)"
        assert dict(self.synapse_counts) == \
            {**expected, "rg_laminate_mirror": 2}, "per-tag mismatch"
        assert len(self.idx) == 91, f"neuron count {len(self.idx)} != 91"
        assert len(self.inputs) == 10, f"port count {len(self.inputs)} != 10"
        assert len(self.muscle_outputs) == 12, "muscle outputs != 12"

    # ------------------------------------------------------------------ run
    def compile(self, dt: float = DT):
        self.compiled = self.net.compile(dt=dt, backend="numpy")
        # FIXED-tau_h stepper for the RG persistent-Na h-gates (AnimatLab /
        # Deng semantics; see module docstring + SNS_NumpyFixedTau)
        self.compiled.__class__ = SNS_NumpyFixedTau
        assert self.compiled.V.shape[0] == len(self.idx), "index mismatch"
        return self.compiled

    def step(self, input_currents: np.ndarray) -> np.ndarray:
        self.compiled.forward(list(input_currents))
        return self.compiled.V

    def input_index(self, port: str) -> int:
        return self.inputs.index(port)

    def make_inputs(self) -> np.ndarray:
        return np.zeros(len(self.inputs))


def build(template_path=None, dt: float = DT, gains: dict | None = None) -> W2LNet:
    """Load the bilateralrg template and build + compile the network.

    gains: optional per-key overrides merged over W2L_GAINS (tuning without
    touching the transcribed topology)."""
    if template_path is None:
        template_path = SPINAL / "connectome_templates.json"
    tpl = json.loads(Path(template_path).read_text(encoding="utf-8"))
    if "bilateralrg" not in tpl:
        raise KeyError(f"{template_path}: no 'bilateralrg' key")
    net = W2LNet(template=tpl["bilateralrg"], gains=gains or {})
    net.compile(dt=dt)
    return net


if __name__ == "__main__":
    import io
    import sys
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
    w = build()
    print(f"neurons: {len(w.idx)}  synapses: {w.n_synapses}  "
          f"inputs: {len(w.inputs)}  outputs: {len(w.muscle_outputs)}")
    print("ports:", w.inputs)
    print("ports inject into:", {p: w.port_targets[p] for p in w.inputs})
    print("synapses per tag:", w.synapse_counts)
