"InnerBaseDiameter"=0.98
"D1@Sketch5"="InnerBaseDiameter"
"InnerBaseOuterGroove"= "InnerBaseDiameter" - 0.1
"InnerHingeInnerCurve"= 1
"InnerHingeOuterCurve" = "InnerHingeInnerCurve" + 0.1
"InnerBaseInnerGroove"= "InnerBaseOuterGroove" - 0.2
"InnerHingeWidth"= 1.45
"OuterBaseInnerGroove"= "OuterBaseOuterGroove" - 0.25
"OuterBaseDiameter"= ( ( "InnerHingeOuterCurve" / 2 ) ^ 2 + ( "InnerHingeLength" / 2 ) ^ 2 ) ^ 0.5 * 2
"InnerHingeLength"=1.2
"D1@Boss-Extrude1"="InnerHingeLength"
"OuterBaseOuterGroove" = "OuterBaseDiameter" - 0.2
"D1@Sketch6"="OuterBaseOuterGroove"
"D2@Sketch6"="OuterBaseInnerGroove"
"D3@Sketch6"="OuterBaseDiameter"
"D1@Cut-Extrude1"="InnerHingeWidth"
