"InnerBaseDiameter"=0.98
"InnerBaseOuterGroove"= "InnerBaseDiameter" - 0.1
"InnerHingeInnerCurve"= 1
"InnerHingeOuterCurve"= "InnerHingeInnerCurve" + 0.1
"InnerBaseInnerGroove"= "InnerBaseOuterGroove" - 0.2
"InnerHingeWidth"= 1.45
"OuterBaseDiameter"= ( ( "InnerHingeOuterCurve" / 2 ) ^ 2 + ( "InnerHingeLength" / 2 ) ^ 2 ) ^ 0.5 * 2
"InnerHingeLength"=1.55
"OuterBaseOuterGroove"= "OuterBaseDiameter" - 0.2
"D5@Sketch1"="OuterBaseOuterGroove"
"D6@Sketch1"="OuterBaseInnerGroove"
"OuterHingeOuterDiameter"= "OuterHingeInnerDiameter" + 0.2
"D1@Sketch1"="OuterBaseDiameter"
"OuterHingeInnerDiameter"= "OuterBaseDiameter" + 0.05
"D7@Sketch1"="OuterHingeOuterDiameter"
"D2@Sketch1"="OuterHingeInnerDiameter"
"OuterHingeLength"= 1.3
"D1@Main Body Extrude" = "OuterHingeLength"+0.2
"TibiaConnectionLength" = 1.25
"D1@Tibia Connection Extrude"="TibiaConnectionLength"
"OuterBaseInnerGroove"= "OuterBaseOuterGroove" - 0.25
