function [fitresult, gof, output, valid] = bpaFits(XX20, YY20, ZZ20, XX10, YY10, ZZ10, XX, YY, ZZ, XX40, YY40, ZZ40)
%CREATEFITS(XX20,YY20,ZZ20,XX10,YY10,ZZ10,XX,YY,ZZ,XX40,YY40,ZZ40)
%  Create fits for 10mm, 20mm, and 40mm BPAs using experimental and Festo
%  data. Run after running "BenLawrenceData.m" in the Testing_Data folder.
%
%  Data for 'Exponential 20, Festo' fit:
%      X Input : XX20
%      Y Input : YY20
%      Z Output: ZZ20
%      Validation X: XX20
%      Validation Y: YY20
%      Validation Z: ZZ20
%  Data for 'Exp10, Festo vs Experiment' fit:
%      X Input : XX10
%      Y Input : YY10
%      Z Output: ZZ10
%      Validation X: XX
%      Validation Y: YY
%      Validation Z: ZZ
%  Data for 'Exp10, Experiment vs Festo' fit:
%      X Input : XX
%      Y Input : YY
%      Z Output: ZZ
%      Validation X: XX10
%      Validation Y: YY10
%      Validation Z: ZZ10
%  Data for 'Exponential 40 normalized' fit:
%      X Input : XX40
%      Y Input : YY40
%      Z Output: ZZ40
%      Validation X: XX40
%      Validation Y: YY40
%      Validation Z: ZZ40
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Dec-2023 17:29:42

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 4, 1 );
gof = struct( 'sse', cell( 4, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );
output = cell( 4,1);


%% Fit: 'Exponential 20, Festo'.
[xData, yData, zData] = prepareSurfaceData( XX20, YY20, ZZ20 );

% Set up fittype and options.
ft = fittype( 'a0*(1-exp(-a1.*x))+y.*exp(-a3*(x.^2))', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 0];
opts.MaxFunEvals = 6000;
opts.MaxIter = 4000;
opts.Robust = 'Bisquare';
opts.StartPoint = [-0.1835 8.565 1.633];
opts.TolFun = 1e-07;
opts.TolX = 1e-07;
opts.Upper = [0 Inf Inf];

% Fit model to data.
[fitresult{1}, gof(1), output{1}] = fit( [xData, yData], zData, ft, opts );

% Compare against validation data.
[xValidation, yValidation, zValidation] = prepareSurfaceData( XX20, YY20, ZZ20 );
residual = zValidation - fitresult{1}( xValidation, yValidation );
nNaN = nnz( isnan( residual ) );
residual(isnan( residual )) = [];
sse = norm( residual )^2;
rmse = sqrt( sse/length( residual ) );
sst = norm(zValidation - mean(zValidation))^2;
Rsquare = 1-(sse*(length(residual)-1))/(sst*(length(residual)));
fprintf( 'Goodness-of-validation for ''%s'' fit:\n', 'Exponential 20, Festo' );
fprintf( '    SSE : %f\n', sse );
fprintf( '    RMSE : %f\n', rmse );
fprintf( '    Adj. R^2 : %f\n', Rsquare );
fprintf( '    Largest residual: %f\n',max(residual));
fprintf( '    %i points outside domain of data.\n', nNaN );

valid(1,:) = table(sse, rmse, sst, Rsquare);

% Create a figure for the plots.
figure( 'Name', 'Exponential 20, Festo' );

% Compute limits for axes.
xlim = [min( [xData; xValidation] ), max( [xData; xValidation] )];
ylim = [min( [yData; yValidation] ), max( [yData; yValidation] )];

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult{1}, [xData, yData], zData, 'XLim', xlim, 'YLim', ylim );
% Add validation data to plot.
hold on
h(end+1) = plot3( xValidation, yValidation, zValidation, 'bo', 'MarkerFaceColor', 'w' );
hold off
legend( h, 'Exponential 20, Festo', 'ZZ20 vs. XX20, YY20', 'ZZ20 vs. XX20, YY20', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'XX20', 'Interpreter', 'none' );
ylabel( 'YY20', 'Interpreter', 'none' );
zlabel( 'ZZ20', 'Interpreter', 'none' );
grid on
view( 0.0, 0.0 );

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult{1}, [xData, yData], zData, 'Style', 'Residual', 'XLim', xlim, 'YLim', ylim );
% Add validation data to plot.
hold on
h(end+1) = plot3( xValidation, yValidation, zValidation - fitresult{1}( xValidation, yValidation ), 'bo', 'MarkerFaceColor', 'w' );
hold off
legend( h, 'Exponential 20, Festo - residuals', 'Exponential 20, Festo - validation residuals', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'XX20', 'Interpreter', 'none' );
ylabel( 'YY20', 'Interpreter', 'none' );
zlabel( 'ZZ20', 'Interpreter', 'none' );
grid on
view( 0.0, 0.0 );

%% Fit: 'Exp10, Festo vs Experiment'.
[xData, yData, zData] = prepareSurfaceData( XX10, YY10, ZZ10 );

% Set up fittype and options.
ft = fittype( 'a0*(1-exp(-a1.*x))+y.*exp(-a3*(x.^2))', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 0];
opts.MaxFunEvals = 6000;
opts.MaxIter = 3000;
opts.Robust = 'Bisquare';
opts.StartPoint = [-0.4039 6.269 0.9842];
opts.Upper = [0 Inf Inf];

% Fit model to data.
[fitresult{2}, gof(2), output{2}] = fit( [xData, yData], zData, ft, opts );

% Compare against validation data.
[xValidation, yValidation, zValidation] = prepareSurfaceData( XX, YY, ZZ );
residual = zValidation - fitresult{2}( xValidation, yValidation );
nNaN = nnz( isnan( residual ) );
residual(isnan( residual )) = [];
sse = norm( residual )^2;
rmse = sqrt( sse/length( residual ) );
sst = norm(zValidation - mean(zValidation))^2;
Rsquare = 1-(sse*(length(residual)-1))/(sst*(length(residual)));
fprintf( 'Goodness-of-validation for ''%s'' fit:\n', 'Exp10, Festo vs Experiment' );
fprintf( '    SSE : %f\n', sse );
fprintf( '    RMSE : %f\n', rmse );
fprintf( '    Adj. R^2 : %f\n', Rsquare );
fprintf( '    Largest residual: %f\n',max(residual));
fprintf( '    %i points outside domain of data.\n', nNaN );

valid(2,:) = table(sse, rmse, sst, Rsquare);

% Create a figure for the plots.
figure( 'Name', 'Exp10, Festo vs Experiment' );

% Compute limits for axes.
xlim = [min( [xData; xValidation] ), max( [xData; xValidation] )];
ylim = [min( [yData; yValidation] ), max( [yData; yValidation] )];

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult{2}, [xData, yData], zData, 'XLim', xlim, 'YLim', ylim );
% Add validation data to plot.
hold on
h(end+1) = plot3( xValidation, yValidation, zValidation, 'bo', 'MarkerFaceColor', 'w' );
hold off
legend( h, 'Exp10, Festo vs Experiment', 'ZZ10 vs. XX10, YY10', 'ZZ vs. XX, YY', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'XX10', 'Interpreter', 'none' );
ylabel( 'YY10', 'Interpreter', 'none' );
zlabel( 'ZZ10', 'Interpreter', 'none' );
grid on
view( 90.0, 0.0 );

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult{2}, [xData, yData], zData, 'Style', 'Residual', 'XLim', xlim, 'YLim', ylim );
% Add validation data to plot.
hold on
h(end+1) = plot3( xValidation, yValidation, zValidation - fitresult{2}( xValidation, yValidation ), 'bo', 'MarkerFaceColor', 'w' );
hold off
legend( h, 'Exp10, Festo vs Experiment - residuals', 'Exp10, Festo vs Experiment - validation residuals', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'XX10', 'Interpreter', 'none' );
ylabel( 'YY10', 'Interpreter', 'none' );
zlabel( 'ZZ10', 'Interpreter', 'none' );
grid on
view( 90.0, 0.0 );

%% Fit: 'Exp10, Experiment vs Festo'.
[xData, yData, zData] = prepareSurfaceData( XX, YY, ZZ );

% Set up fittype and options.
ft = fittype( 'a0*(1-exp(-a1.*x))+y.*exp(-a3*(x.^2))', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 0];
opts.MaxFunEvals = 6000;
opts.MaxIter = 2000;
opts.Robust = 'Bisquare';
opts.StartPoint = [-0.5756 4.085 0.5497];
opts.Upper = [0 Inf Inf];


% Fit model to data.
[fitresult{3}, gof(3), output{3}] = fit( [xData, yData], zData, ft, opts );

% Compare against validation data.
[xValidation, yValidation, zValidation] = prepareSurfaceData( XX10, YY10, ZZ10 );
residual = zValidation - fitresult{3}( xValidation, yValidation );
nNaN = nnz( isnan( residual ) );
residual(isnan( residual )) = [];
sse = norm( residual )^2;
rmse = sqrt( sse/length( residual ) );
sst = norm(zValidation - mean(zValidation))^2;
Rsquare = 1-(sse*(length(residual)-1))/(sst*(length(residual)));
fprintf( 'Goodness-of-validation for ''%s'' fit:\n', 'Exp10, Experiment vs Festo' );
fprintf( '    SSE : %f\n', sse );
fprintf( '    RMSE : %f\n', rmse );
fprintf( '    Adj. R^2 : %f\n', Rsquare );
fprintf( '    Largest residual: %f\n',max(residual));
fprintf( '    %i points outside domain of data.\n', nNaN );

valid(3,:) = table(sse, rmse, sst, Rsquare);
% Create a figure for the plots.
figure( 'Name', 'Exp10, Experiment vs Festo' );

% Compute limits for axes.
xlim = [min( [xData; xValidation] ), max( [xData; xValidation] )];
ylim = [min( [yData; yValidation] ), max( [yData; yValidation] )];

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult{3}, [xData, yData], zData, 'XLim', xlim, 'YLim', ylim );
% Add validation data to plot.
hold on
h(end+1) = plot3( xValidation, yValidation, zValidation, 'bo', 'MarkerFaceColor', 'w' );
hold off
legend( h, 'Exp10, Experiment vs Festo', 'ZZ vs. XX, YY', 'ZZ10 vs. XX10, YY10', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'XX', 'Interpreter', 'none' );
ylabel( 'YY', 'Interpreter', 'none' );
zlabel( 'ZZ', 'Interpreter', 'none' );
grid on
view( 90.0, 0.0 );

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult{3}, [xData, yData], zData, 'Style', 'Residual', 'XLim', xlim, 'YLim', ylim );
% Add validation data to plot.
hold on
h(end+1) = plot3( xValidation, yValidation, zValidation - fitresult{3}( xValidation, yValidation ), 'bo', 'MarkerFaceColor', 'w' );
hold off
legend( h, 'Exp10, Experiment vs Festo - residuals', 'Exp10, Experiment vs Festo - validation residuals', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'XX', 'Interpreter', 'none' );
ylabel( 'YY', 'Interpreter', 'none' );
zlabel( 'ZZ', 'Interpreter', 'none' );
grid on
view( 90.0, 0.0 );

%% Fit: 'Exponential 40 normalized'.
[xData, yData, zData] = prepareSurfaceData( XX40, YY40, ZZ40 );

% Set up fittype and options.
ft = fittype( 'a0*(1-exp(-a1.*x))+y.*exp(-a2.*x.^2)', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 0];
opts.MaxFunEvals = 6000;
opts.MaxIter = 4000;
opts.Robust = 'Bisquare';
opts.StartPoint = [-0.119 10.83 2.141];
opts.Upper = [0 Inf Inf];


% Fit model to data.
[fitresult{4}, gof(4), output{4}] = fit( [xData, yData], zData, ft, opts );

% Compare against validation data.
[xValidation, yValidation, zValidation] = prepareSurfaceData( XX40, YY40, ZZ40 );
residual = zValidation - fitresult{4}( xValidation, yValidation );
nNaN = nnz( isnan( residual ) );
residual(isnan( residual )) = [];
sse = norm( residual )^2;
rmse = sqrt( sse/length( residual ) );
sst = norm(zValidation - mean(zValidation))^2;
Rsquare = 1-(sse*(length(residual)-1))/(sst*(length(residual)));
fprintf( 'Goodness-of-validation for ''%s'' fit:\n', 'Exponential 40 normalized' );
fprintf( '    SSE : %f\n', sse );
fprintf( '    RMSE : %f\n', rmse );
fprintf( '    Adj. R^2 : %f\n', Rsquare );
fprintf( '    Largest residual: %f\n',max(residual));
fprintf( '    %i points outside domain of data.\n', nNaN );

valid(4,:) = table(sse, rmse, sst, Rsquare);
% Create a figure for the plots.
figure( 'Name', 'Exponential 40 normalized' );

% Compute limits for axes.
xlim = [min( [xData; xValidation] ), max( [xData; xValidation] )];
ylim = [min( [yData; yValidation] ), max( [yData; yValidation] )];

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult{4}, [xData, yData], zData, 'XLim', xlim, 'YLim', ylim );
% Add validation data to plot.
hold on
h(end+1) = plot3( xValidation, yValidation, zValidation, 'bo', 'MarkerFaceColor', 'w' );
hold off
legend( h, 'Exponential 40 normalized', 'ZZ40 vs. XX40, YY40', 'ZZ40 vs. XX40, YY40', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'XX40', 'Interpreter', 'none' );
ylabel( 'YY40', 'Interpreter', 'none' );
zlabel( 'ZZ40', 'Interpreter', 'none' );
grid on
view( 0.0, 0.0 );

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult{4}, [xData, yData], zData, 'Style', 'Residual', 'XLim', xlim, 'YLim', ylim );
% Add validation data to plot.
hold on
h(end+1) = plot3( xValidation, yValidation, zValidation - fitresult{4}( xValidation, yValidation ), 'bo', 'MarkerFaceColor', 'w' );
hold off
legend( h, 'Exponential 40 normalized - residuals', 'Exponential 40 normalized - validation residuals', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'XX40', 'Interpreter', 'none' );
ylabel( 'YY40', 'Interpreter', 'none' );
zlabel( 'ZZ40', 'Interpreter', 'none' );
grid on
view( 0.0, 0.0 );


