%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\Github\Muscle_Sensory\BPA_Static_Characterization_Test\20mm_maxForce\BPA Test Results.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 01-Apr-2026 11:16:38

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "C5:F62";

% Specify column names and types
opts.VariableNames = ["Var3", "Var4", "Var5", "Var6"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Import the data
BPATestResults = readtable("D:\Github\Muscle_Sensory\BPA_Static_Characterization_Test\20mm_maxForce\BPA Test Results.xlsx", opts, "UseExcel", false);

%% Convert to output type
BPATestResults = table2array(BPATestResults);
kmax20 = BPATestResults(:,[1 2 4]);
kmax20 = sortrows(kmax20,1,"ascend");

%% Clear temporary variables
clear opts