function [obj, grad] = generatedObjective(inputVariables)
%generatedObjective Compute objective function value
%
%   This function computes the objective value.
%   Update the generated code to add the objective gradient computation.
%
%   OBJ = generatedObjective(INPUTVARIABLES) computes the objective value
%   OBJ at the point INPUTVARIABLES.
%
%   [OBJ, GRAD] = generatedObjective(INPUTVARIABLES) additionally computes
%   the objective gradient value GRAD at the current point.
%
%   Auto-generated by prob2struct on 08-May-2024 02:45:29

%% Variable indices.
kBidx = 1;
kTidx = 2;
x1idx = 3;

%% Map solver-based variables to problem-based.
kB = inputVariables(kBidx);
kT = inputVariables(kTidx);
x1 = inputVariables(x1idx);

%% Insert gradient calculation here.
% To call the gradient code, notify the solver by setting the
% SpecifyObjectiveGradient option to true.
if nargout > 1
    if nargout > 1
        grad = [];
    end
end

%% Compute objective function.
[arg2,~] = generatedFunction_minimizeFlx1_withReuse(x1, kT, kB);
obj = arg2(2);

end