openfig('MaxForce10_all.fig');
ax1=gca;
openfig('MaxForce10.fig')
ax2=gca;
openfig('MaxForce20.fig');
ax3=gca;
openfig('kmax10.fig')
ax4=gca;
 
figure;
tcl=tiledlayout(2,2);
ax1.Parent=tcl;
ax1.Layout.Tile=1;
ax2.Parent=tcl;
ax2.Layout.Tile=2;
ax3.Parent=tcl;
ax3.Layout.Tile=3;
ax4.Parent=tcl;
ax4.Layout.Tile=4;