%% Compare Martens and Sarosi models to ours
% Compare at arbitrary lrest of 150 mm, 300 mm, and 450 mm
clear; clc; close all

lrest = [.15, .3, .45];
%% Load our data
load allData.mat XX YY ZZ xTrain yTrain zTrain xVal yVal zVal
load data20mm_sorted.mat Ax Ay Az xTrain20 yTrain20 zTrain20 xVal20 yVal20 zVal20
load FestoLookup.mat f_10 f20

%% Redimensionalize force and pressure
%Calculate max force for resting lengths
Fmax10 = maxBPAforce(lrest,'10',620); %10 mm
Fmax20 = maxBPAforce(lrest,'20',620); %20 mm

%Redimensionalize force
Z10 = Fmax10'*ZZ';
Z10 = Z10';
Z20 = Fmax20'*Az';
Z20 = Z20';

%Sort it for the curve fitter
Z10_150 = Z10(:,1); %10 mm
Z10_300 = Z10(:,2);
Z10_450 = Z10(:,3);
Z20_150 = Z20(:,1); %20 mm
Z20_300 = Z20(:,2);
Z20_450 = Z20(:,3);

%Redimensionalize pressure
P10 = YY*620;
P20 = 620*Ay;
%% Sarosi coefficients
a10 = [-9.2194029, 203.7012413, -0.34221042, -3.2255991, 109.2038216, -208.372034]; %From https://publicatio.bibl.u-szeged.hu/22381/1/scientific_bulletin_2012.pdf
a20a = [-4.00180705, 292.4620246, -0.32930845, -9.33564098, 294.0538256, -280.498151]; %20 mm diameter 200 mm resting length From "New Force Functions for the Force Generated by Different Fluidic Muscles József Sárosi 2012 https://publicatio.bibl.u-szeged.hu/22104/7/2179838_publikacio.pdf 
a20b = [-4.35573, 281.22370, -0.32866, -9.27035, 302.20107, -263.69185]; %Sarosi 2017, 20 mm diameter and 400 mm resting length. Reported previously in "New Force Functions for the Force Generated by Different Fluidic Muscles József Sárosi 2012" https://publicatio.bibl.u-szeged.hu/22104/7/2179838_publikacio.pdf

[Sar10_1, Sar10_2, Sar10_3, sark10] = sar(lrest,10,a10,XX,YY);
[Sar20_1a, Sar20_2a, Sar20_3a, sark20a] = sar(lrest,20,a20a,Ax,Ay);
[Sar20_1b, Sar20_2b, Sar20_3b, sark20b] = sar(lrest,20,a20b,Ax,Ay);

%% Martens and Boblan coefficients
%Coeff.
% Converted to Pa and m from [MPa, MPA/m, GPa/m^2, MPa/m^3, deg(?)]
c10 = [74.085*10^6 -689.20*10^6 1.837*10^9  -848.79*10^6 -0.1]; %10 mm
c20 = [93.232*10^6 -715.29*10^6 1.5483*10^9 -502.95*10^6 -0.073]; %20 mm

k10 = (0.25 - 0.198)/0.25;   % 0.208 from Martens Table A2
k20 = (0.30 - 0.222)/0.30;   % 0.260 from Martens Table A1

[Mar10_1, Mar10_2, Mar10_3, L10] = Martens(lrest,10,c10,XX,YY,k10);
[Mar20_1, Mar20_2, Mar20_3, L20] = Martens(lrest,20,c20,Ax,Ay,k20);


%%  Our model
B10_150 = f_10(XX,YY).*maxBPAforce(lrest(1),'10',620);
B10_300 = f_10(XX,YY).*maxBPAforce(lrest(2),'10',620);
B10_450 = f_10(XX,YY).*maxBPAforce(lrest(3),'10',620);

B20_150 = f20(XX,YY).*maxBPAforce(lrest(1),'20',620);
B20_300 = f20(XX,YY).*maxBPAforce(lrest(2),'20',620);
B20_450 = f20(XX,YY).*maxBPAforce(lrest(3),'20',620);



% save ModelCompare.mat

%% Sarosi function
function [FF1, FF2, FF3, kmax] = sar(rest,dia,u,x,y)
%rest = resting length;
%dia = diameter
%u = coefficients
%relative contraction
%y = pressure
myfun = @(K,Pmax,a,b,c,d,e,f)(a*Pmax+b)*exp(c*K)+d*Pmax*K+e*Pmax+f; 
a = u(1);
b = u(2);
c = u(3);
d = u(4);
e = u(5);
f = u(6);
Pmax = 620;
fun = @(K) myfun(K,Pmax,a,b,c,d,e,f);
kmax = fzero(fun,[14 35]);          %Find kmax. Sarosi apparently uses contraction percent and not decimal.

% kmax10 = 0.2; %as seen graphically in https://publicatio.bibl.u-szeged.hu/22381/1/scientific_bulletin_2012.pdf
% kmax20 = []; %Solve using fzero?
p = y*620;  %kPa

k = x*kmax;     %convert relative strain to actual. x is normalized 0-1; Sarosi model uses contraction in percent.
FF = (a*p+b).*exp(c*k)+d*p.*k+e*p+f;
FF1 = FF(:,1);
FF2 = FF(:,1);
FF3 = FF(:,1);
end


%% Martens and Boblan model 
function varargout = Martens(rest,d,c,x,y,kappa)
% Martens force model
%
% Inputs
%   rest  : 1xn vector of resting lengths [m]
%   d     : initial inner diameter [mm]
%   c     : coefficient vector [c0 c1 c2 c3 d0]
%   x     : Nx1 normalized contraction input
%   y     : Nx1 pressure normalized by 620 kPa
%   kappa : maximum contraction fraction for this diameter
%
% Outputs
%   FF = Martens(...)
%       returns FF as Nx nRest
%
%   [FF1,FF2,...,FFn] = Martens(...)
%       returns one Nx1 force vector per resting length
%
%   [FF1,...,FFn,L] = Martens(...)
%       also returns:
%           L    as Nx nRest

    % ---------- basic checks ----------
    rest = rest(:).';   % force row
    x = x(:);           % normalized contraction
    y = y(:);           % pressure normalized by 620 kPa

    nRest = numel(rest);
    N = numel(x);

    if numel(y) ~= N
        error('x and y must have the same number of elements.');
    end

    if numel(c) ~= 5
        error('c must be a 1x5 vector: [c0 c1 c2 c3 d0].');
    end

    % ---------- coefficients ----------
    c0 = c(1);
    c1 = c(2);
    c2 = c(3);
    c3 = c(4);
    d0 = c(5);

    % ---------- constants ----------
    t0    = 28.6;           % initial fiber angle [deg]
    tcorr = t0 + d0;        % corrected fiber angle [deg]
    H0    = 0.0018;         % initial membrane thickness [m]

    % Convert diameter to meters
    if d > 1
        D0 = d / 1000;      % initial inner diameter [m]
    else
        D0 = d;
    end

    p = 620e3 * y;          % Pressure redimensionalized [Pa]

    % ---------- geometry ----------
    L0     = rest;                              % initial length [m]
    Lfiber = L0 ./ cosd(tcorr);                 % fiber length, constant [m]
    n      = L0 .* tand(tcorr) ./ (pi * D0);   % number of fiber windings

    % ---------- convert x -> L ----------
    % Use the published Martens force-map contraction range for each diameter:
    %   DMSP-10-250: kappa = (0.25 - 0.198)/0.25 = 0.208
    %   DMSP-20-300: kappa = (0.30 - 0.222)/0.30 = 0.260
    %
    % Thus x = 0 corresponds to L = L0,
    % and x = 1 corresponds to L = L0*(1-kappa).

    L = L0 .* (1 - kappa .* x);                 % muscle length [m], Nx nRest

    % ---------- evaluate force ----------
    D = sqrt(Lfiber.^2 - L.^2) ./ (n*pi);       % diameter as a function of length [m]

    derV = (Lfiber.^2 - 3*L.^2) ./ (4*pi*n.^2); % derivative dV/dL
    derD = -(L ./ sqrt(Lfiber.^2 - L.^2)) ./ (n*pi); % derivative dD/dL

    Eru = c3.*L.^3 + c2.*L.^2 + c1.*L + c0;     % modulus of elasticity [Pa]

    sigL  = Eru .* (L - L0) ./ L0;              % tension in length direction [Pa]
    sigPE = Eru .* (D - D0) ./ D0;              % tension in perimeter direction [Pa]

    FL  = sigL  .* H0 .* pi .* D;               % force to deform membrane in length direction [N]
    FPE = sigPE .* H0 .* L  .* pi;              % force to deform membrane perimeter [N]

    FF = -p .* derV + FPE .* derD - FL;         % Martens force [N]

    % ---------- output logic ----------
    if nargout == 1
        varargout{1} = FF;

    elseif nargout == nRest
        for k = 1:nRest
            varargout{k} = FF(:,k);
        end

    elseif nargout == nRest + 1
        for k = 1:nRest
            varargout{k} = FF(:,k);
        end
        varargout{nRest+1} = L;

    else
        error(['Invalid number of outputs. Use one of these patterns:\n' ...
               '  FF = Martens(...)\n' ...
               '  [FF1,...,FFn] = Martens(...) where n = numel(rest)\n' ...
               '  [FF1,...,FFn,L] = Martens(...)']);
    end
end