%% Compare Martens and Sarosi models to ours
% Compare at arbitrary lrest of 150 mm, 300 mm, and 450 mm
clear; clc; close all

lrest = [.15, .3, .45];
%% Load our data
load allData.mat XX YY ZZ xTrain yTrain zTrain xVal yVal zVal
load data20mm_sorted.mat Ax Ay Az xTrain20 yTrain20 zTrain20 xVal20 yVal20 zVal20
load FestoLookup.mat f_10 f20

%% Redimensionalize force and pressure
%Calculate max force for resting lengths
Fmax10 = maxBPAforce(lrest,'10',620); %10 mm
Fmax20 = maxBPAforce(lrest,'20',620); %20 mm

%Redimensionalize force
Z10 = Fmax10'*ZZ';
Z10 = Z10';
Z20 = Fmax20'*Az';
Z20 = Z20';

%Sort it for the curve fitter
Z10_150 = Z10(:,1); %10 mm
Z10_300 = Z10(:,2);
Z10_450 = Z10(:,3);
Z20_150 = Z20(:,1); %20 mm
Z20_300 = Z20(:,2);
Z20_450 = Z20(:,3);

%Redimensionalize pressure
P10 = YY*620;
P20 = 620*Ay;

%% %%  Our model
B10_150 = f_10(XX,YY).*maxBPAforce(lrest(1),'10',620);
B10_300 = f_10(XX,YY).*maxBPAforce(lrest(2),'10',620);
B10_450 = f_10(XX,YY).*maxBPAforce(lrest(3),'10',620);

B20_150 = f20(Ax,Ay).*maxBPAforce(lrest(1),'20',620);
B20_300 = f20(Ax,Ay).*maxBPAforce(lrest(2),'20',620);
B20_450 = f20(Ax,Ay).*maxBPAforce(lrest(3),'20',620);

%% Sarosi coefficients
a10 = [-9.2194029, 203.7012413, -0.34221042, -3.2255991, 109.2038216, -208.372034]; %From https://publicatio.bibl.u-szeged.hu/22381/1/scientific_bulletin_2012.pdf
a20a = [-4.00180705, 292.4620246, -0.32930845, -9.33564098, 294.0538256, -280.498151]; %20 mm diameter 200 mm resting length From "New Force Functions for the Force Generated by Different Fluidic Muscles József Sárosi 2012 https://publicatio.bibl.u-szeged.hu/22104/7/2179838_publikacio.pdf 
a20b = [-4.35573, 281.22370, -0.32866, -9.27035, 302.20107, -263.69185]; %Sarosi 2017, 20 mm diameter and 400 mm resting length. Reported previously in "New Force Functions for the Force Generated by Different Fluidic Muscles József Sárosi 2012" https://publicatio.bibl.u-szeged.hu/22104/7/2179838_publikacio.pdf

[Sar10_1, Sar10_2, Sar10_3, sark10] = sar(lrest,10,a10,XX,YY);
[Sar20_1a, Sar20_2a, Sar20_3a, sark20a] = sar(lrest,20,a20a,Ax,Ay);
[Sar20_1b, Sar20_2b, Sar20_3b, sark20b] = sar(lrest,20,a20b,Ax,Ay);

%% Martens and Boblan coefficients
%Coeff.
% Converted to Pa and m from [MPa, MPA/m, GPa/m^2, MPa/m^3, deg(?)]
c10 = [74.085*10^6 -689.20*10^6 1.837*10^9  -848.79*10^6 -0.1]; %10 mm
c20 = [93.232*10^6 -715.29*10^6 1.5483*10^9 -502.95*10^6 -0.073]; %20 mm

k10 = (0.25 - 0.198)/0.25;   % 0.208 from Martens Table A2
k20 = (0.30 - 0.222)/0.30;   % 0.260 from Martens Table A1

[Mar10_1, Mar10_2, Mar10_3, L10] = Martens(lrest,13.6,c10,XX,YY,k10);
[Mar20_1, Mar20_2, Mar20_3, L20] = Martens(lrest,23.6,c20,Ax,Ay,k20);

%Compare Martens and Boblan to his own force map
% Appendix A1: DMSP-20-300 measured force map
L_A1 = [0.296 0.282 0.267 0.250 0.237 0.222];   % [m]

P_A1 = [ ...
     35000
     65000
     85000
    110000
    135000
    146250
    157500
    168750
    180000
    197500
    215000
    232500
    250000
    281250
    312500
    343750
    375000
    450000
    525000
    600000
    675000];                                    % [Pa]

F_A1 = [ ...
      0      0      0      0      0      0
    54.9     0      0      0      0      0
   113.4     0      0      0      0      0
   179.0     0      0      0      0      0
   241.8     0      0      0      0      0
   273.3   21.1     0      0      0      0
   300.2   42.9     0      0      0      0
   331.0   70.3     0      0      0      0
   355.6   93.7     0      0      0      0
   402.5  131.0   27.7     0      0      0
   446.5  165.2   61.6     0      0      0
   495.9  204.1   92.7     0      0      0
   543.4  244.7  122.0     0      0      0
   623.5  309.7  170.2   42.8     0      0
   708.8  380.4  221.0   80.6     0      0
   787.9  443.7  277.4  118.7     0      0
   870.9  518.9  328.0  157.6     0      0
  1065.2  676.4  462.3  252.1   65.5     0
  1268.9  837.5  587.8  352.3  124.7     0
  1460.1 1004.0  714.8  443.5  188.1     0
  1653.5 1164.3  840.7  535.8  253.3     0];

% Table A2 for DMSP-10-250
L_A2 = [0.250 0.234 0.219 0.204 0.198];   % [m]

P_A2 = [ ...
     50000
     68750
    132500
    196250
    260000
    285000
    310000
    335000
    360000
    402187
    441375
    486562
    528750
    559062
    589375
    619688
    650000];   % [Pa]

F_A2 = [ ...
      0        0        0        0       0
    32.1667    0        0        0       0
    84.8333    0        0        0       0
   139.5       0        0        0       0
   195.6667    0        0        0       0
   217.6667   17        0        0       0
   239.6667   35.1667   0        0       0
   261.6667   52.6667   0        0       0
   283.8333   71.3333   0        0       0
   321.5     101.5     22.8333   0       0
   359.0     132.3333  46.1667   0       0
   396.6667  162.5     69.3333   0       0
   434.3333  193.6667  92.1667   0       0
   461.6667  216.3333 109.3333  11.5     0
   488.3333  238.1667 126.3333  23.3333  0
   515.8333  261.0    142.6667  35.0     0
   542.5     282.8333 158.6667  46.0     0];

%20 mm debug
L0_test = [0.300, 0.296];      % [m]
d_test  = [20, 21.8];          % [mm]

errPct  = nan(numel(L0_test), numel(d_test));
rmseDbg = nan(numel(L0_test), numel(d_test));
fvuDbg  = nan(numel(L0_test), numel(d_test));
maxDbg  = nan(numel(L0_test), numel(d_test));

for iL0 = 1:numel(L0_test)
    for iD = 1:numel(d_test)
        F_dbg = Martens_PL(L0_test(iL0), d_test(iD), c20, P_A1, L_A1);
        F_dbg = max(F_dbg, 0);   % clamp if you want tensile-force comparison

        [rmseDbg(iL0,iD), fvuDbg(iL0,iD), maxDbg(iL0,iD)] = Go_OfF(F_A1(:), F_dbg(:));
        errPct(iL0,iD) = 100 * max(abs(F_A1(:) - F_dbg(:))) / max(F_A1(:));

        fprintf('L0 = %.3f m, d = %.1f mm --> RMSE = %.4f, FVU = %.4f, MaxResid = %.4f, errPct = %.4f%%\n', ...
            L0_test(iL0), d_test(iD), rmseDbg(iL0,iD), fvuDbg(iL0,iD), maxDbg(iL0,iD), errPct(iL0,iD));
    end
end

disp('Rows = L0 = [0.300, 0.296], Cols = d = [20, 21.8]')
disp('errPct = ')
disp(errPct)
disp('RMSE = ')
disp(rmseDbg)
disp('FVU = ')
disp(fvuDbg)
disp('MaxResid = ')
disp(maxDbg)

F_300_20   = max(Martens_PL(0.300, 20.0, c20, P_A1, L_A1), 0);
F_300_21p8 = max(Martens_PL(0.300, 21.8, c20, P_A1, L_A1), 0);
F_296_20   = max(Martens_PL(0.296, 20.0, c20, P_A1, L_A1), 0);
F_296_21p8 = max(Martens_PL(0.296, 21.8, c20, P_A1, L_A1), 0);

figure('Name','Martens A1 debug sweep');
tiledlayout(2,2)

Fset = {F_300_20, F_300_21p8, F_296_20, F_296_21p8};
titles = {'L0=0.300, d=20', 'L0=0.300, d=21.8', 'L0=0.296, d=20', 'L0=0.296, d=21.8'};

[PP_A1,LL_A1] = ndgrid(P_A1/1000, L_A1);

for k = 1:4
    nexttile
    scatter3(LL_A1(:), PP_A1(:), F_A1(:), 24, 'filled'); hold on
    scatter3(LL_A1(:), PP_A1(:), Fset{k}(:), 16);
    grid on
    xlabel('Length (m)')
    ylabel('Pressure (kPa)')
    zlabel('Force (N)')
    title(titles{k})
    legend('Measured A1','Model','Location','best')
end

% % Native Martens validation on the exact published grids
% F_M10_A2 = Martens_PL(0.250,10,c10,P_A2,L_A2);
% F_M20_A1 = Martens_PL(0.296,20,c20,P_A1,L_A1);
% 
% F_M10_A2 = max(F_M10_A2,0);
% F_M20_A1 = max(F_M20_A1,0);
% 
% errPct_A2 = 100 * max(abs(F_A2(:) - F_M10_A2(:))) / max(F_A2(:));
% errPct_A1 = 100 * max(abs(F_A1(:) - F_M20_A1(:))) / max(F_A1(:));
% 
% % Scaling diagnostic (Martens) ---
% 
% alpha_A2 = (F_A2(:)' * F_M10_A2(:)) / (F_M10_A2(:)' * F_M10_A2(:));
% alpha_A1 = (F_A1(:)' * F_M20_A1(:)) / (F_M20_A1(:)' * F_M20_A1(:));
% 
% F_M10_A2_scaled = alpha_A2 * F_M10_A2;
% F_M20_A1_scaled = alpha_A1 * F_M20_A1;
% 
% errPct_A2_scaled = 100 * max(abs(F_A2(:) - F_M10_A2_scaled(:))) / max(F_A2(:));
% errPct_A1_scaled = 100 * max(abs(F_A1(:) - F_M20_A1_scaled(:))) / max(F_A1(:));
% 
% disp('--- Martens scaling diagnostic ---')
% disp([alpha_A2, errPct_A2, errPct_A2_scaled])
% disp([alpha_A1, errPct_A1, errPct_A1_scaled])

% %Plot the native checks
% [PP_A2,LL_A2g] = ndgrid(P_A2/1000, L_A2);   % pressure in kPa for plotting
% [PP_A1,LL_A1g] = ndgrid(P_A1/1000, L_A1);
% 
% figure('Name','Martens native validation');
% tiledlayout(2,2)
% 
% nexttile
% scatter3(LL_A2g(:), PP_A2(:), F_A2(:), 30, 'filled'); hold on
% scatter3(LL_A2g(:), PP_A2(:), F_M10_A2(:), 20);
% grid on
% xlabel('Length (m)')
% ylabel('Pressure (kPa)')
% zlabel('Force (N)')
% title('DMSP-10-250: measured vs model')
% legend('Measured A2','Martens model','Location','best')
% 
% nexttile
% scatter3(LL_A2g(:), PP_A2(:), F_A2(:)-F_M10_A2(:), 30, 'filled')
% grid on
% xlabel('Length (m)')
% ylabel('Pressure (kPa)')
% zlabel('Residual (N)')
% title(sprintf('DMSP-10-250 residual, err = %.2f%%', errPct_A2))
% 
% nexttile
% scatter3(LL_A1g(:), PP_A1(:), F_A1(:), 30, 'filled'); hold on
% scatter3(LL_A1g(:), PP_A1(:), F_M20_A1(:), 20);
% grid on
% xlabel('Length (m)')
% ylabel('Pressure (kPa)')
% zlabel('Force (N)')
% title('DMSP-20-300: measured vs model')
% legend('Measured A1','Martens model','Location','best')
% 
% nexttile
% scatter3(LL_A1g(:), PP_A1(:), F_A1(:)-F_M20_A1(:), 30, 'filled')
% grid on
% xlabel('Length (m)')
% ylabel('Pressure (kPa)')
% zlabel('Residual (N)')
% title(sprintf('DMSP-20-300 residual, err = %.2f%%', errPct_A1))


%% Compare all models
% iL = resting length index: 1=150 mm, 2=300 mm, 3=450 mm
% iM = model index: 1=Bolen, 2=Martens, 3=Sarosi
% iD = diameter index: 1=10 mm, 2=20 mm

True = cell(3,2);      % {iL,iD}
Pred = cell(3,3,2);    % {iL,iM,iD}

% ----- true data -----
True{1,1} = Z10_150(:);
True{2,1} = Z10_300(:);
True{3,1} = Z10_450(:);

True{1,2} = Z20_150(:);
True{2,2} = Z20_300(:);
True{3,2} = Z20_450(:);

Bolen = {
    B10_150(:), B20_150(:);
    B10_300(:), B20_300(:);
    B10_450(:), B20_450(:)};

Mar = {
    Mar10_1(:), Mar20_1(:);
    Mar10_2(:), Mar20_2(:);
    Mar10_3(:), Mar20_3(:)};

Sarosi = {
    Sar10_1(:), Sar20_1a(:);
    Sar10_2(:), Sar20_2b(:);
    Sar10_3(:), Sar20_3b(:)};

for iL = 1:3
    for iD = 1:2
        Pred{iL,1,iD} = Bolen{iL,iD};
        Pred{iL,2,iD} = Mar{iL,iD};
        Pred{iL,3,iD} = Sarosi{iL,iD};
    end
end

GoF = nan(3,3,2,3);   % length x model x diameter x metric

for iD = 1:2
    for iL = 1:3
        ytrue = True{iL,iD};

        for iM = 1:3
            val = Pred{iL,iM,iD};

            if numel(ytrue) ~= numel(val)
                error('Size mismatch at iL=%d, iM=%d, iD=%d: true=%d, pred=%d', ...
                    iL, iM, iD, numel(ytrue), numel(val));
            end

            [rmse,fvu,maxResid] = Go_OfF(ytrue,val);
            GoF(iL,iM,iD,:) = [rmse,fvu,maxResid];
        end
    end
end

CaseLabel = {
    '10 mm, 150 mm'
    '10 mm, 300 mm'
    '10 mm, 450 mm'
    '20 mm, 150 mm'
    '20 mm, 300 mm'
    '20 mm, 450 mm'};

rowDiam = [10;10;10;20;20;20];
rowRest = [150;300;450;150;300;450];

Tdata = nan(6,9);
row = 0;

for iD = 1:2
    for iL = 1:3
        row = row + 1;
        Tdata(row,:) = [ ...
            squeeze(GoF(iL,1,iD,:)).', ...
            squeeze(GoF(iL,2,iD,:)).', ...
            squeeze(GoF(iL,3,iD,:)).' ];
    end
end

ResultsTable = table( ...
    CaseLabel, rowDiam, rowRest, ...
    Tdata(:,1), Tdata(:,2), Tdata(:,3), ...
    Tdata(:,4), Tdata(:,5), Tdata(:,6), ...
    Tdata(:,7), Tdata(:,8), Tdata(:,9), ...
    'VariableNames', { ...
    'Case','Diameter_mm','RestLength_mm', ...
    'Bolen_RMSE','Bolen_FVU','Bolen_MaxError', ...
    'Martens_RMSE','Martens_FVU','Martens_MaxError', ...
    'Sarosi_RMSE','Sarosi_FVU','Sarosi_MaxError'});

%% Figures to visualize it

%% 10 mm BPA figure
figure('Name','10 mm BPA comparison');
tiledlayout(2,3)

% 150 mm
nexttile
scatter3(XX,YY,Z10_150,20,'filled'); hold on
scatter3(XX,YY,B10_150,20);
scatter3(XX,YY,Mar10_1,20);
scatter3(XX,YY,Sar10_1,20);
grid on
xlabel('Normalized contraction')
ylabel('Normalized pressure')
zlabel('Force (N)')
title('10 mm, 150 mm')
legend('Data','Bolen','Martens','Sarosi','Location','best')

% 300 mm
nexttile
scatter3(XX,YY,Z10_300,20,'filled'); hold on
scatter3(XX,YY,B10_300,20);
scatter3(XX,YY,Mar10_2,20);
scatter3(XX,YY,Sar10_2,20);
grid on
xlabel('Normalized contraction')
ylabel('Normalized pressure')
zlabel('Force (N)')
title('10 mm, 300 mm')
legend('Data','Bolen','Martens','Sarosi','Location','best')

% 450 mm
nexttile
scatter3(XX,YY,Z10_450,20,'filled'); hold on
scatter3(XX,YY,B10_450,20);
scatter3(XX,YY,Mar10_3,20);
scatter3(XX,YY,Sar10_3,20);
grid on
xlabel('Normalized contraction')
ylabel('Normalized pressure')
zlabel('Force (N)')
title('10 mm, 450 mm')
legend('Data','Bolen','Martens','Sarosi','Location','best')

% residuals: Bolen
nexttile
scatter3(XX,YY,Z10_150-B10_150,20,'filled'); hold on
scatter3(XX,YY,Z10_300-B10_300,20,'filled');
scatter3(XX,YY,Z10_450-B10_450,20,'filled');
grid on
xlabel('Normalized contraction')
ylabel('Normalized pressure')
zlabel('Residual (N)')
title('10 mm residuals: Bolen')
legend('150 mm','300 mm','450 mm','Location','best')

% residuals: Martens
nexttile
scatter3(XX,YY,Z10_150-Mar10_1,20,'filled'); hold on
scatter3(XX,YY,Z10_300-Mar10_2,20,'filled');
scatter3(XX,YY,Z10_450-Mar10_3,20,'filled');
grid on
xlabel('Normalized contraction')
ylabel('Normalized pressure')
zlabel('Residual (N)')
title('10 mm residuals: Martens')
legend('150 mm','300 mm','450 mm','Location','best')

% residuals: Sarosi
nexttile
scatter3(XX,YY,Z10_150-Sar10_1,20,'filled'); hold on
scatter3(XX,YY,Z10_300-Sar10_2,20,'filled');
scatter3(XX,YY,Z10_450-Sar10_3,20,'filled');
grid on
xlabel('Normalized contraction')
ylabel('Normalized pressure')
zlabel('Residual (N)')
title('10 mm residuals: Sarosi')
legend('150 mm','300 mm','450 mm','Location','best')


%% 20 mm BPA figure
figure('Name','20 mm BPA comparison');
tiledlayout(2,3)

% 150 mm
nexttile
scatter3(Ax,Ay,Z20_150,20,'filled'); hold on
scatter3(Ax,Ay,B20_150,20);
scatter3(Ax,Ay,Mar20_1,20);
scatter3(Ax,Ay,Sar20_1a,20);
grid on
xlabel('Normalized contraction')
ylabel('Normalized pressure')
zlabel('Force (N)')
title('20 mm, 150 mm')
legend('Data','Bolen','Martens','Sarosi','Location','best')

% 300 mm
nexttile
scatter3(Ax,Ay,Z20_300,20,'filled'); hold on
scatter3(Ax,Ay,B20_300,20);
scatter3(Ax,Ay,Mar20_2,20);
scatter3(Ax,Ay,Sar20_2b,20);
grid on
xlabel('Normalized contraction')
ylabel('Normalized pressure')
zlabel('Force (N)')
title('20 mm, 300 mm')
legend('Data','Bolen','Martens','Sarosi','Location','best')

% 450 mm
nexttile
scatter3(Ax,Ay,Z20_450,20,'filled'); hold on
scatter3(Ax,Ay,B20_450,20);
scatter3(Ax,Ay,Mar20_3,20);
scatter3(Ax,Ay,Sar20_3b,20);
grid on
xlabel('Normalized contraction')
ylabel('Normalized pressure')
zlabel('Force (N)')
title('20 mm, 450 mm')
legend('Data','Bolen','Martens','Sarosi','Location','best')

% residuals: Bolen
nexttile
scatter3(Ax,Ay,Z20_150-B20_150,20,'filled'); hold on
scatter3(Ax,Ay,Z20_300-B20_300,20,'filled');
scatter3(Ax,Ay,Z20_450-B20_450,20,'filled');
grid on
xlabel('Normalized contraction')
ylabel('Normalized pressure')
zlabel('Residual (N)')
title('20 mm residuals: Bolen')
legend('150 mm','300 mm','450 mm','Location','best')

% residuals: Martens
nexttile
scatter3(Ax,Ay,Z20_150-Mar20_1,20,'filled'); hold on
scatter3(Ax,Ay,Z20_300-Mar20_2,20,'filled');
scatter3(Ax,Ay,Z20_450-Mar20_3,20,'filled');
grid on
xlabel('Normalized contraction')
ylabel('Normalized pressure')
zlabel('Residual (N)')
title('20 mm residuals: Martens')
legend('150 mm','300 mm','450 mm','Location','best')

% residuals: Sarosi
nexttile
scatter3(Ax,Ay,Z20_150-Sar20_1a,20,'filled'); hold on
scatter3(Ax,Ay,Z20_300-Sar20_2b,20,'filled');
scatter3(Ax,Ay,Z20_450-Sar20_3b,20,'filled');
grid on
xlabel('Normalized contraction')
ylabel('Normalized pressure')
zlabel('Residual (N)')
title('20 mm residuals: Sarosi')
legend('150 mm','300 mm','450 mm','Location','best')


%% Save work as this but don't have it autosave.

% save ModelCompare.mat

%% Sarosi function
function [FF1, FF2, FF3, kmax] = sar(rest,dia,u,x,y)
%rest = resting length;
%dia = diameter
%u = coefficients
%relative contraction
%y = pressure
myfun = @(K,Pmax,a,b,c,d,e,f)(a*Pmax+b)*exp(c*K)+d*Pmax*K+e*Pmax+f; 
a = u(1);
b = u(2);
c = u(3);
d = u(4);
e = u(5);
f = u(6);
Pmax = 6.2;     % bar
fun = @(K) myfun(K,Pmax,a,b,c,d,e,f);
kmax = fzero(fun,[14 35]);          %Find kmax. Sarosi apparently uses contraction percent and not decimal.

% kmax10 = 0.2; %as seen graphically in https://publicatio.bibl.u-szeged.hu/22381/1/scientific_bulletin_2012.pdf
% kmax20 = []; %Solve using fzero?
p = y*6.2;  % bar

k = x*kmax;     %convert relative strain to actual. x is normalized 0-1; Sarosi model uses contraction in percent.
FF = (a*p+b).*exp(c*k)+d*p.*k+e*p+f;
FF1 = FF(:,1);
FF2 = FF(:,1);
FF3 = FF(:,1);
end


%% Martens and Boblan model 
function varargout = Martens(rest,d,c,x,y,kappa)
% Martens force model
%
% Inputs
%   rest  : 1xn vector of resting lengths [m]
%   d     : initial inner diameter [mm]
%   c     : coefficient vector [c0 c1 c2 c3 d0]
%   x     : Nx1 normalized contraction input
%   y     : Nx1 pressure normalized by 620 kPa
%   kappa : maximum contraction fraction for this diameter
%
% Outputs
%   FF = Martens(...)
%       returns FF as Nx nRest
%
%   [FF1,FF2,...,FFn] = Martens(...)
%       returns one Nx1 force vector per resting length
%
%   [FF1,...,FFn,L] = Martens(...)
%       also returns:
%           L    as Nx nRest

    % ---------- basic checks ----------
    rest = rest(:).';   % make sure the input is a row array
    x = x(:);           % normalized contraction
    y = y(:);           % pressure normalized by 620 kPa

    nRest = numel(rest);
    N = numel(x);

    if numel(y) ~= N
        error('x and y must have the same number of elements.');
    end

    if numel(c) ~= 5
        error('c must be a 1x5 vector: [c0 c1 c2 c3 d0].');
    end

    % ---------- coefficients ----------
    c0 = c(1);
    c1 = c(2);
    c2 = c(3);
    c3 = c(4);
    d0 = c(5);

    % ---------- constants ----------
    t0    = 28.6;           % initial fiber angle [deg]
    tcorr = t0 + d0;        % corrected fiber angle [deg]
    H0    = 0.0018;         % initial membrane thickness [m]

    % Convert diameter to meters
    if d > 1
        D0 = d / 1000;      % initial inner diameter [m]
    else
        D0 = d;
    end

    p = 620e3 * y;          % Pressure redimensionalized [Pa]

    % ---------- geometry ----------
    L0     = rest;                              % initial length [m]
    Lfiber = L0 ./ cosd(tcorr);                 % fiber length, constant [m]
    n      = L0 .* tand(tcorr) ./ (pi * D0);   % number of fiber windings

    % ---------- convert x -> L ----------
    % Use the published Martens force-map contraction range for each diameter:
    %   DMSP-10-250: kappa = (0.25 - 0.198)/0.25 = 0.208
    %   DMSP-20-300: kappa = (0.30 - 0.222)/0.30 = 0.260
    %
    % Thus x = 0 corresponds to L = L0,
    % and x = 1 corresponds to L = L0*(1-kappa).

    L = L0 .* (1 - kappa .* x);                 % muscle length [m], Nx nRest

    % ---------- evaluate force ----------
    D = sqrt(Lfiber.^2 - L.^2) ./ (n*pi);       % diameter as a function of length [m]

    derV = (Lfiber.^2 - 3*L.^2) ./ (4*pi*n.^2); % derivative dV/dL
    derD = -(L ./ sqrt(Lfiber.^2 - L.^2)) ./ (n*pi); % derivative dD/dL

    Eru = c3.*L.^3 + c2.*L.^2 + c1.*L + c0;     % modulus of elasticity [Pa]

    sigL  = Eru .* (L - L0) ./ L0;              % tension in length direction [Pa]
    sigPE = Eru .* (D - D0) ./ D0;              % tension in perimeter direction [Pa]

    FL  = sigL  .* H0 .* pi .* D;               % force to deform membrane in length direction [N]
    FPE = sigPE .* H0 .* L  .* pi;              % force to deform membrane perimeter [N]

    FF = -p .* derV + FPE .* derD - FL;         % Martens force [N]

    % ---------- output logic ----------
    if nargout == 1
        varargout{1} = FF;

    elseif nargout == nRest
        for k = 1:nRest
            varargout{k} = FF(:,k);
        end

    elseif nargout == nRest + 1
        for k = 1:nRest
            varargout{k} = FF(:,k);
        end
        varargout{nRest+1} = L;

    else
        error(['Invalid number of outputs. Use one of these patterns:\n' ...
               '  FF = Martens(...)\n' ...
               '  [FF1,...,FFn] = Martens(...) where n = numel(rest)\n' ...
               '  [FF1,...,FFn,L] = Martens(...)']);
    end
end

%% Direct Martens evaluation helper function
function [F, Fp, FpeTerm, FlTerm] = Martens_PL(L0,d,c,P,L)
% Direct Martens evaluation on absolute pressure-length grid
%
% Inputs:
%   L0 : initial length [m]
%   d  : initial inner diameter [mm]
%   c  : [c0 c1 c2 c3 d0]
%   P  : pressure values [Pa], column vector
%   L  : length values [m], row vector
%
% Output:
%   F  : force map [N], size numel(P)-by-numel(L)

    c0 = c(1);
    c1 = c(2);
    c2 = c(3);
    c3 = c(4);
    d0 = c(5);

    t0    = 28.6;           % initial fiber angle [deg]
    tcorr = t0 + d0;        % corrected fiber angle [deg]
    H0    = 0.0018;         % initial membrane thickness [m]
    D0    = d/1000;         % initial inner diameter [m]

    Lfiber = L0 ./ cosd(tcorr);               % fiber length, constant [m]
    n      = L0 .* tand(tcorr) ./ (pi*D0);    % number of fiber windings

    [PP,LL] = ndgrid(P,L);

    D    = sqrt(Lfiber.^2 - LL.^2) ./ (n*pi);                % diameter as function of length [m]
    dVdL = (Lfiber.^2 - 3*LL.^2) ./ (4*pi*n.^2);             % derivative dV/dL
    dDdL = -(LL ./ sqrt(Lfiber.^2 - LL.^2)) ./ (n*pi);       % derivative dD/dL

    Eru = c3.*LL.^3 + c2.*LL.^2 + c1.*LL + c0;               % modulus of elasticity [Pa]

    sigL  = Eru .* (LL - L0) ./ L0;                          % tension in length direction [Pa]
    sigPE = Eru .* (D - D0) ./ D0;                           % tension in perimeter direction [Pa]

    FL  = sigL  .* H0 .* pi .* D;                            % force to deform membrane in length direction [N]
    FPE = sigPE .* H0 .* LL .* pi;                           % force to deform membrane perimeter [N]

    Fp      = -PP .* dVdL;
    FpeTerm = FPE .* dDdL;
    FlTerm  = -FL;

    F = Fp + FpeTerm + FlTerm;
    % F = -PP .* dVdL + FPE .* dDdL - FL;                      % Martens force [N] -PP .* dVdL + FPE .* dDdL - FL

    % Optional for comparison to tensile force tables:
    F = max(F,0);
end