% Bi Pulley Specs From Masters
% Author: Ben Bolen
% Date: 2026-09-24
% Description: Builds BiPam_pulley muscle-spec structs from the master's-era
% attachment data on disk at "D:\Bipedal humanoid\Matlab code". Each spec
% carries the route points (grouped by body frame exactly as BiPamData expects:
% rows before Cross(1) in the proximal frame, rows Cross(1)..Cross(2)-1 in the
% middle frame, rows Cross(2)..end in the distal frame), the two-hinge
% kinematic data needed to build the 4-D TransformationMat, and the Fmax
% source. The driver (Opt_run_BiPulley) owns the transforms; this builder
% only extracts and documents the data.
%
% WHAT IS ACTUALLY THERE (inspected 2026-09-24):
%   D:\Bipedal humanoid\Matlab code\AttachPoints_Robot.mat
%       All muscle attachment / wrapping points as named 3x1 doubles in
%       METERS, grouped per body (p1..p10 pelvis, f1..f5 femur, t1..t6 and
%       twr1..twr3 tibia, a1..a8 calcn/toes, b1..b4 torso, plus per-muscle
%       *_wr* wrap points). Generated by AttachPoints_Robot.m in the same
%       folder.
%   D:\Bipedal humanoid\Matlab code\PAM_Prop.mat
%       Per-ROBOT-muscle max isometric force `<name>_mif` (N), e.g.
%       semimem_mif = 1698 (aggregated), med_gas_mif = 1558,
%       rect_fem_mif = 1169, tfl_mif = 233. Generated by PAM_Prop.m.
%   D:\Bipedal humanoid\Matlab code\MovePoints.mat
%       Rolling-knee data: knee_angle_x/knee_x (12 pts) and
%       knee_angle_y/knee_y (7 pts) samples of the knee-center location vs
%       knee angle (the same data behind the fcn1/fcn2 curve fits used by
%       bipedal_kinematics_bi_hip.m line 100, p_k = [fcn1(theta_k);
%       fcn2(theta_k); 0]). The raw grids are loaded (not the cfit objects)
%       so no Curve Fitting Toolbox dependency exists at run time.
%
% MAPPING DECISIONS (documented per the batch contract):
%   - Route formulas follow the master's own length formulas in
%     bipedal_kinematics_bi_hip.m (semimem line 125, tfl line 156,
%     rect_fem line 186, med_gas line 198), but points are grouped by BODY
%     so the BiPam_pulley class handles the frame transforms.
%   - rect_fem: the master's patella path point pa1 is a knee-angle function
%     from MovePoints (bipedal_kinematics_bi_hip.m line 185,
%     pa1 = [fcn3(theta_k); fcn4(theta_k); 0.002]), not a fixed attachment;
%     the builder substitutes the fixed tibia point t3 ("connects patella"),
%     i.e. a RIGID PATELLA approximation. This is the same wrap-as-via
%     spirit as the OpenSim builder's simplification.
%   - med_gas: the master's length formula has NO tibia via point (femur f4
%     directly to calcn a1, line 198), so both crossings fall on the same
%     row (Cross = [3 3], the BiPamData duplicate-crossing case);
%     BiPam_pulley chains the two transforms child-to-parent in that case.
%     The extra femur via med_gas_wr1 (AttachPoints_Robot.m line 104,
%     "%femur", posterior distal femur) IS added on top of the formula --
%     it exists in the attachment file specifically for med_gas and keeps
%     the routed path from clipping the knee; document or drop it when
%     comparing torques against the master's raw lengths.
%   - twr1 is treated as a TIBIA point (per the AttachPoints_Robot.m Tibia
%     section, line 33, where it sits with t1..t6) even though the
%     commented master's LENGTH formula transforms it with T_h; the
%     master's commented formulas are internally inconsistent about this
%     (the knee moment arm, line 129, reads twr1 in the T_k child = tibia
%     frame, and norm(t1-twr1) is computed with no transform at all), and
%     the file's section grouping is followed.
%
% Usage:
%   specs = biPulleySpecsFromMasters();            % default 4-muscle set
%   specs = biPulleySpecsFromMasters({'semimem_r', 'med_gas_r'});
%   specs = biPulleySpecsFromMasters({}, mastersDir);  % custom data dir
%   specs = biPulleySpecsFromMasters([], [], struct('nPulleyBPA', 2));

function specs = biPulleySpecsFromMasters(names, mastersDir, pulleyConfig)

%% Inputs and data location
if nargin < 1 || isempty(names)
    % Keep the default set SHORT and genuinely biarticular (right side).
    names = {'semimem_r', 'rect_fem_r', 'med_gas_r', 'tfl_r'};
end
if nargin < 2 || isempty(mastersDir)
    mastersDir = 'D:\Bipedal humanoid\Matlab code';
end
if nargin < 3
    pulleyConfig = struct();
end

attachFile = fullfile(mastersDir, 'AttachPoints_Robot.mat');
pamFile = fullfile(mastersDir, 'PAM_Prop.mat');
moveFile = fullfile(mastersDir, 'MovePoints.mat');
if ~exist(attachFile, 'file')
    error('biPulleySpecsFromMasters:missingData', ...
        'Master''s attachment data not found at %s', attachFile)
end
if ~exist(pamFile, 'file')
    error('biPulleySpecsFromMasters:missingData', ...
        'Master''s PAM properties not found at %s', pamFile)
end

S = load(attachFile);
P = load(pamFile);

%% Route table
% Each row: {specName, mifField, frameNames, pointNames, nProximal, nMiddle}
% pointNames are variable names in AttachPoints_Robot.mat, ordered as the
% route: proximal-frame rows, middle-frame rows, distal-frame rows.
routes = { ...
    'semimem_r',  'semimem_mif',  {'pelvis', 'femur', 'tibia'}, ...
        {'p5', 'semimem_wr1', 'semimem_wr2', 'twr1', 't1', 't6'}, 1, 2; ...
    'rect_fem_r', 'rect_fem_mif', {'pelvis', 'femur', 'tibia'}, ...
        {'p10', 'rect_fem_wr1', 'rect_fem_wr2', 'rect_fem_wr3', 't3'}, 1, 3; ...
    'med_gas_r',  'med_gas_mif',  {'femur', 'tibia', 'calcn'}, ...
        {'f4', 'med_gas_wr1', 'a1'}, 2, 0; ...
    'tfl_r',      'tfl_mif',      {'pelvis', 'femur', 'tibia'}, ...
        {'p3', 'tfl_wr1', 'tfl_wr2', 't2', 't5'}, 1, 2};

%% Two-hinge kinematics shared by the pelvis-femur-tibia routes
% From bipedal_kinematics_bi_hip.m: hip hinge about +z through
% p_h = [-0.0707; -0.0661; 0.0835] (pelvis coords, line 99, R_h_z form);
% knee hinge about +z through the rolling knee center (femur coords,
% p_k = [fcn1; fcn2; 0], line 100, R_k line 76). Ankle (knee-ankle routes)
% about the master's ankle axis omg_a (line 83) through
% p_a = [0; -0.43; 0] (tibia coords, line 103). Joint ranges from the
% master's RoM block (lines 14-23): hip [-15, 110], knee [-120, 10],
% ankle [-50, 20] deg.
pHip = [-0.0707; -0.0661; 0.0835];
pAnkle = [0; -0.43; 0];
omgAnkle = [-0.10501355; -0.17402245; 0.97912632];  % master's ankle axis
thetaHipKnee = [-15, 110; -120, 10];    % [joint1; joint2], deg
thetaKneeAnkle = [-120, 10; -50, 20];

% Rolling-knee grids (knee center in femur coords vs knee angle, rad).
% Defaults keep the knee FIXED at the neutral sample when MovePoints.mat is
% unavailable; the builder warns in that case.
kneeFit = struct('thetaX', [], 'x', [], 'thetaY', [], 'y', []);
if exist(moveFile, 'file')
    M = load(moveFile, 'knee_angle_x', 'knee_x', 'knee_angle_y', 'knee_y');
    kneeFit.thetaX = M.knee_angle_x(:).';
    kneeFit.x = M.knee_x(:).';
    kneeFit.thetaY = M.knee_angle_y(:).';
    kneeFit.y = M.knee_y(:).';
else
    warning('biPulleySpecsFromMasters:noMovePoints', ...
        'MovePoints.mat not found; knee pivot held fixed at the neutral sample.')
    kneeFit.thetaX = 0;
    kneeFit.x = 0.047;
    kneeFit.thetaY = 0;
    kneeFit.y = -0.113;
end

% Joint ranges are set per route below (hip/knee vs knee/ankle chains).

%% Build one spec per requested name
nSpec = numel(names);
specs = struct([]);   %#ok<STRNU>
for k = 1:nSpec
    row = find(strcmp(routes(:, 1), names{k}), 1);
    if isempty(row)
        error('biPulleySpecsFromMasters:unknownMuscle', ...
            'No master''s route named %s. Available: %s', ...
            names{k}, strjoin(routes(:, 1), ', '))
    end

    pointNames = routes{row, 4};
    nPts = numel(pointNames);
    pts = zeros(nPts, 3);
    for j = 1:nPts
        if ~isfield(S, pointNames{j})
            error('biPulleySpecsFromMasters:missingPoint', ...
                'AttachPoints_Robot.mat has no variable %s (route %s)', ...
                pointNames{j}, names{k})
        end
        pts(j, :) = S.(pointNames{j}).';
    end

    nProx = routes{row, 5};
    nMid = routes{row, 6};
    cross = [nProx + 1, nProx + nMid + 1];   % BiPamData Cross convention

    mifField = routes{row, 2};
    if ~isfield(P, mifField)
        error('biPulleySpecsFromMasters:missingMif', ...
            'PAM_Prop.mat has no variable %s (route %s)', mifField, names{k})
    end

    % Per-route hinge pivots/axes (rows = joint 1 then joint 2). Pivots are
    % expressed in the PARENT frame of each joint, matching RpToTrans. The
    % rolling knee center is evaluated at theta = 0 for the fixed-pivot
    % fallback; kin.kneeFit carries the full angle-dependent center.
    kneeNeutral = [interp1(kneeFit.thetaX, kneeFit.x, 0), ...
        interp1(kneeFit.thetaY, kneeFit.y, 0), 0];
    if strcmp(routes{row, 3}{1}, 'pelvis')
        pivot1 = pHip';                     % hip, pelvis coords (1x3)
        pivot2 = kneeNeutral;               % knee, femur coords
        axis2 = [0, 0, 1];
        thetaRanges = thetaHipKnee;
    else
        pivot1 = kneeNeutral;               % med_gas: joint 1 = knee (femur)
        pivot2 = pAnkle';                   % joint 2 = ankle, tibia coords
        axis2 = omgAnkle';
        thetaRanges = thetaKneeAnkle;
    end

    spec = struct();
    spec.name = names{k};
    spec.source = 'masters';
    spec.points = pts;
    spec.cross = cross;
    spec.frames = routes{row, 3};
    spec.diameter = 20;

    % Transmission config (defaults 1 / 1 / 'moving_via'); passed through
    % to BiPam_pulley's 15th argument by the driver. No bundle placement
    % here: the master's routes are single-line BPA routes (a parallel
    % bundle would be a NEW mechanical design, not master's data).
    spec.pulley = struct( ...
        'nPulleyBPA', cfgField(pulleyConfig, 'nPulleyBPA', 1), ...
        'tackleLineParts', cfgField(pulleyConfig, 'tackleLineParts', 1), ...
        'routingMode', cfgField(pulleyConfig, 'routingMode', 'moving_via'));
    spec.bundleOffsets = zeros(0, 3);
    spec.bundleMargin = 0.005;
    spec.footprintWidth = spec.diameter * 1e-3;

    spec.fmax = P.(mifField);
    spec.fmaxSource = sprintf('PAM_Prop.mat %s', mifField);
    spec.kin.pivots = [pivot1; pivot2];     % 2x3, parent-frame coords
    spec.kin.axes = [0, 0, 1; axis2];       % 2x3 unit rotation axes
    spec.kin.types = {'hinge', 'hinge'};
    spec.kin.thetaRangesDeg = thetaRanges;
    if strcmp(routes{row, 3}{1}, 'pelvis')
        spec.kin.kneeSlot = 2;              % knee = joint 2
    else
        spec.kin.kneeSlot = 1;              % med_gas: knee = joint 1
    end
    spec.kin.kneeFit = kneeFit;             % rolling knee center (femur coords)
    spec.kin.pointFolds = {[0; 0; 0], [0; 0; 0]};   % no folds needed
    spec.notes = sprintf(['master''s route %s: points [%s]; knee center ' ...
        'from MovePoints grids (rolling knee); patella approximated rigid ' ...
        'for rect_fem via t3'], names{k}, strjoin(pointNames, ' '));

    if isempty(specs)
        specs = spec;
    else
        specs(end + 1) = spec;   %#ok<AGROW>
    end
end

end

%% ---------------------------------------------------------------------
function val = cfgField(cfg, name, default)
% Config field with default (used for the transmission config).
if isfield(cfg, name)
    val = cfg.(name);
else
    val = default;
end
end
